### ISSUE TITLE
TERMUX ERROR 

### ISSUE THREAD

**Issue by ghost** [rahnumaa18/https-github.com-avramit-Instahack#5]
Hello need help :

Traceback (most recent call last):
  File "hackinsta.py", line 154, in <module>
    sess = instabrute.Login(password)
  File "hackinsta.py", line 114, in Login
    sess.headers.update({'X-CSRFToken' : r.cookies.get_dict()['csrftoken']})
KeyError: 'csrftoken'

**Comment by mukush** [comment]
I have same problem ......are you get the solution?

**Comment by ghost** [comment]
Sorry I did not see that at first, but thanks you.
